### ISSUE TITLE
Dark Theme improvment

### ISSUE THREAD

**Issue by benavern** [typicode/hotel#135]
Hi!
First, thank you for this awesome tool that I use everyday.
I really like dark themes when I'm coding, in all my tools, this is why I use the [Stylish chrome extension](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe) that permits me to inject css in webpages. This is what I do for google and other websites, I use it for hotel too.
I did want to share the css I inject inside Hotel & ask you if you could think in a dark theme feature.
(I could make a PR if you want...)

Here is the code : 

``` css
#app,
aside,
main {
    background-color: #333;
    color: #eee;
    overflow-y: auto;
}

aside {
    border-right: 2px solid #555;
}

li small {
    color: #aaa;
}

button.logs.selected {
    color: #14B8CC;
}

footer {
    display: none;
}

#down {
    position: fixed;
    top: auto;
    bottom: 20px;
    right: 40px;
    background-color: #555;
    width: 50px;
    height: 50px;
    border-radius: 25px;
    line-height: 55px;
    text-align: center;
    box-shadow: 0 0 5px #111;
    transform: scale(1);
    opacity: .2;
    transition: all .3s;
}

#down:hover {
    color: #eee;
    box-shadow: 0 0 10px 5px #111;
    transform: scale(1.1);
    opacity: 1;
}
```

The result : 

![hotel](https://cloud.githubusercontent.com/assets/5999900/19022395/36fb05a2-88d8-11e6-928b-2b887a6eace4.png)

Looking forward to an answer, 
Benjamin
